// Different types of GameAction, with each different type telling us how the action props should be handled.
export const ActionType = {
  MOVE: 0,
  ROTATE: 1,
  MOVE_TO: 2,
  FLIP: 3,
  DROP: 4,
  PLACE: 5,
  HOLD: 6,
};

// A wrapper class whose instances are generated by keydown user input events
export class GameAction {
  constructor(type, props) {
    this.type = type;
    this.props = props;
  }
}
